<project xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>io.github.r4fterman</groupId>
        <artifactId>com.windowtester</artifactId>
        <version>6.0.3-SNAPSHOT</version>
    </parent>

    <artifactId>com.windowtester.runtime</artifactId>
    <name>WindowTester Runtime</name>
    <description>The runtime library providing base functionality so WindowTester can operate on a
        screen.
    </description>

    <scm>
        <connection>scm:git:https://github.com/r4fterman/windowtester.git</connection>
        <developerConnection>scm:git:https://github.com/r4fterman/windowtester.git
        </developerConnection>
        <url>https://github.com/r4fterman/windowtester</url>
    </scm>

    <dependencies>
        <dependency>
            <groupId>io.github.r4fterman</groupId>
            <artifactId>abbot</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-engine</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>build-helper-maven-plugin</artifactId>
                <version>3.5.0</version>
                <executions>
                    <execution>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>add-source</goal>
                        </goals>
                        <configuration>
                            <sources>
                                <source>com.windowtester.runtime/src/main/java</source>
                            </sources>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>dev.dimlight</groupId>
                <artifactId>shellcheck-maven-plugin</artifactId>
                <configuration>
                    <skip>true</skip>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
