#!/usr/bin/env bash
set -euo pipefail

extensions=(
  "java"
  "json"
  "md"
)
ext_regex="\\.($(IFS='|'; echo "${extensions[*]}"))$"

# command taken from https://github.com/JLLeitschuh/ktlint-gradle  task addKtlintFormatGitPreCommitHook
# Identify modified files that are not deleted and match the specified extensions
filesToFormat=$(git --no-pager diff --name-status --no-color --cached \
  | awk -v regex="$ext_regex" '$1 != "D" && $2 ~ regex { print $NF }')


if [ -z "$filesToFormat" ]; then
    exit 0
fi

mvn spotless:apply

for fileToFormat in $filesToFormat
do
  git add "$fileToFormat"
done;