<project xmlns="http://maven.apache.org/POM/4.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>io.github.r4fterman</groupId>
    <artifactId>com.windowtester</artifactId>
    <version>5.14.1-SNAPSHOT</version>
  </parent>

  <artifactId>com.windowtester.swing.recorder</artifactId>
  <name>Windowtester Recorder</name>
  <description>The recorder library provides functionality to record a manual UI interaction and replay it automatically.</description>

  <scm>
    <connection>scm:git:https://github.com/r4fterman/windowtester.git</connection>
    <developerConnection>scm:git:https://github.com/r4fterman/windowtester.git</developerConnection>
    <url>https://github.com/r4fterman/windowtester</url>
  </scm>

  <dependencies>
    <dependency>
      <groupId>io.github.r4fterman</groupId>
      <artifactId>abbot</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>io.github.r4fterman</groupId>
      <artifactId>com.windowtester.swing.runtime</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>io.github.r4fterman</groupId>
      <artifactId>com.windowtester.junit5</artifactId>
      <version>${project.version}</version>
      <scope>test</scope>
    </dependency>
  </dependencies>
</project>
