<project xmlns="http://maven.apache.org/POM/4.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>io.github.r4fterman</groupId>
    <artifactId>com.windowtester</artifactId>
    <version>5.14.1-SNAPSHOT</version>
  </parent>

  <artifactId>abbot</artifactId>
  <name>Windowtester Abbot</name>
  <description>Abbot provides robot functionality to interact with the UI.</description>

  <scm>
    <connection>scm:git:https://github.com/r4fterman/windowtester.git</connection>
    <developerConnection>scm:git:https://github.com/r4fterman/windowtester.git</developerConnection>
    <url>https://github.com/r4fterman/windowtester</url>
  </scm>

  <dependencies>
    <dependency>
      <groupId>org.junit.platform</groupId>
      <artifactId>junit-platform-suite</artifactId>
      <version>1.10.1</version>
    </dependency>

    <dependency>
      <groupId>gnu-regexp</groupId>
      <artifactId>gnu-regexp</artifactId>
      <version>1.1.4</version>
    </dependency>
      <dependency>
          <groupId>org.dom4j</groupId>
          <artifactId>dom4j</artifactId>
          <version>2.2.0</version>
      </dependency>
  </dependencies>

  <build>
    <plugins>
      <plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>build-helper-maven-plugin</artifactId>
        <executions>
          <execution>
            <phase>generate-sources</phase>
            <goals>
              <goal>add-source</goal>
            </goals>
            <configuration>
              <sources>
                <source>abbot/src/main/java</source>
              </sources>
            </configuration>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
</project>
