/*******************************************************************************
 *  Copyright (c) 2012 Google, Inc.
 *  All rights reserved. This program and the accompanying materials
 *  are made available under the terms of the Eclipse Public License v1.0
 *  which accompanies this distribution, and is available at
 *  http://www.eclipse.org/legal/epl-v10.html
 *
 *  Contributors:
 *  Google, Inc. - initial API and implementation
 *******************************************************************************/
package com.windowtester.internal.runtime.monitor;

import com.windowtester.internal.debug.IRuntimePluginTraceOptions;
import com.windowtester.internal.debug.Logger;
import com.windowtester.internal.debug.ThreadUtil;
import com.windowtester.runtime.IUIContext;
import com.windowtester.runtime.condition.IConditionMonitor;
import com.windowtester.runtime.monitor.IUIThreadMonitor;
import com.windowtester.runtime.monitor.IUIThreadMonitorListener;
import com.windowtester.runtime.util.ScreenCapture;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.TreeSet;

/**
 * Abstract superclass providing common behavior for objects that monitor the UI Thread and notifies
 * listeners if the UI thread is either hung or idle for an extended period of time. Typically this
 * is accomplished by launching a background thread (minimum priority) that checks to see if the UI
 * is responsive and processing input. If the UI becomes unresponsive or idle for a period longer
 * than expected, then the associated
 * {@link com.windowtester.runtime.monitor.IUIThreadMonitorListener} (see
 * {@link
 * com.windowtester.runtime.monitor.IUIThreadMonitor#setListener(com.windowtester.runtime.monitor.IUIThreadMonitorListener)})
 * is notified.
 */
public abstract class UIThreadMonitorCommon implements IUIThreadMonitor {

  // Tracing Constants
  private static final int TRACE_UNINITIALIZED = 0;
  private static final int TRACE_OFF = 1;
  private static final int TRACE_ON = 2;
  private static final int TRACE_CONSOLE = 3;

  private static int traceMode = TRACE_UNINITIALIZED;

  /**
   * The user interface context used by the receiver to handle conditions when the UI thread has
   * been idle too long in an attempt to get the test running again.
   */
  private final IUIContext uiContext;

  /**
   * The object to synchronize against when accessing the {@link #listener},
   * {@link #defaultExpectedDelay}, {@link #uiThreadResponsive}, {@link #uiEventProcessed} and
   * {@link #uiBusyUntil} fields.
   */
  protected final Object lock = new Object();

  /**
   * The listener associated with the receiver that will be notified if the UI is no longer
   * responsive and processing input. Synchronize against {@link #lock} when accessing this field.
   */
  private IUIThreadMonitorListener listener;

  /**
   * Default expected delay... 2 minutes unless overridden by a call to
   * {@link #setDefaultExpectedDelay(long)}. Synchronize against {@link #lock} when accessing this
   * field.
   */
  private long defaultExpectedDelay = 120_000;

  /**
   * Flag indicating that the UI is responsive. Synchronize against {@link #lock} when accessing
   * this field.
   */
  protected boolean uiThreadResponsive;

  /**
   * Flag indicating that the UI is processing events. Synchronize against {@link #lock} when
   * accessing this field.
   */
  private boolean uiEventProcessed;

  /**
   * The system time before which the UI thread should have processed a new event. This is set as
   * needed during test execution by calling {@link #expectDelay(long)}. Synchronize against
   * {@link #lock} when accessing this field.
   */
  private long uiBusyUntil;

  /**
   * Stack traces at time of UI inactivity generated by {@link #fireUITimeout(boolean)} and consumed
   * by {@link #writeResults(PrintWriter, boolean)}
   */
  private String stackTraces;

  /**
   * Screen capture at time of UI inactivity generated by {@link #fireUITimeout(boolean)} and
   * consumed by {@link #writeResults(PrintWriter, boolean)}
   */
  private File screenCapture;

  /**
   * Construct a new instance to monitor the health of the user interface thread.
   *
   * @param uiContext the user interface context (not <code>null</code>)
   */
  protected UIThreadMonitorCommon(IUIContext uiContext) {
    if (uiContext == null) {
      throw new IllegalArgumentException();
    }
    this.uiContext = uiContext;
  }

  /**
   * Answer the current thread monitor listener.
   *
   * @return the listener or <code>null</code> if none.
   */
  protected IUIThreadMonitorListener getListener() {
    synchronized (lock) {
      return listener;
    }
  }

  @Override
  public void setListener(IUIThreadMonitorListener newListener) {
    com.windowtester.runtime.monitor.IUIThreadMonitorListener oldListener;
    synchronized (lock) {
      oldListener = listener;
      listener = newListener;
    }
    trace("setListener ", newListener);
    if (newListener != null) {
      if (oldListener == null) {
        addEventListeners();
        launchMonitorThread();
      }
    } else {
      if (oldListener != null) {
        removeEventListeners();
      }
    }
  }

  @Override
  public void expectDelay(long millis) {
    long currentTime = System.currentTimeMillis();
    synchronized (lock) {
      uiBusyUntil = currentTime + Math.max(millis, defaultExpectedDelay);
    }
    trace("expect delay ", millis);
  }

  @Override
  public void setDefaultExpectedDelay(long millis) {
    synchronized (lock) {
      long currentTime = System.currentTimeMillis();
      synchronized (lock) {
        defaultExpectedDelay = millis;
        uiBusyUntil = currentTime + defaultExpectedDelay;
      }
    }
    trace("default delay ", defaultExpectedDelay);
  }

  /**
   * Notify the listener that the user interface thread has been idle or unresponsive longer than
   * expected.
   *
   * @param isResponsive <code>true</code> if the UI thread is responsive to new user
   *                     interface events and
   *                     <code>false</code> if the user interface has not processed any new
   *                     events recently as may be hung.
   */
  private void fireUITimeout(boolean isResponsive) {
    var listener = getListener();

    // log current thread state before triggering shutdown
    stackTraces = ThreadUtil.getStackTraces();
    screenCapture = ScreenCapture.createScreenCapture("UIThreadMonitor-timeout");
    Logger.log("UIThreadMonitor: timeout, current thread state\n", stackTraces);

    if (listener != null) {
      var thread =
          new Thread("UIThreadMonitor Notify") {
            @Override
            public void run() {
              listener.uiTimeout(isResponsive);
            }
          };
      thread.setPriority(Thread.MIN_PRIORITY);
      thread.setDaemon(true);
      thread.start();
    }
  }

  /**
   * Attempt to gracefully exit the application
   *
   * @param isResponsive <code>true</code> if the UI thread is responsive to new user
   *                     input, and <code>false</code> if the user interface has not processed any
   *                     new events recently and may be hung.
   */
  protected void gracefulExit(boolean isResponsive) {
    generateResults(isResponsive);
    // TODO [author=Dan] How do we gracefully exit?
    forcedExit(isResponsive);
  }

  /**
   * When all else fails, exit the system
   *
   * @param isResponsive <code>true</code> if the UI thread is responsive to new user
   *                     input, and <code>false</code> if the user interface has not processed any
   *                     new events recently and may be hung.
   */
  protected void forcedExit(boolean isResponsive) {
    var exitMsg = "monitor system exit, isResponsive=" + isResponsive;
    Logger.log(exitMsg);
    trace(exitMsg, null);
    System.exit(9);
  }

  /**
   * Launch a background thread (minimum priority) that checks to see if the UI is still alive and
   * processing input.
   */
  private void launchMonitorThread() {
    var monitorThread =
        new Thread("UIThreadMonitor") {
          @Override
          public void run() {
            initExpectedDelay();
            trace("monitor start", null);

            int checkEventsCount = 0;
            int uiTimeoutCount = 0;
            while (true) {
              if (hasTestEnded()) {
                trace("monitor end 1", null);
                break;
              }

              checkEventsProcessed();
              if (hasTestEnded()) {
                trace("monitor end 2", null);
                break;
              }
              if (wereEventsProcessed()) {
                trace("events processed", null);
                checkEventsCount = 0;
                uiTimeoutCount = 0;
                continue;
              }
              checkEventsCount++;
              if (checkEventsCount <= 10) {
                trace("no events process " + checkEventsCount, null);
                continue;
              }

              boolean isResponsive = isUIThreadResponsive();
              if (hasTestEnded()) {
                trace("monitor end 3", null);
                break;
              }

              if (isResponsive && processConditions()) {
                trace("conditions handled", null);
                continue;
              }
              if (isDelayExpected()) {
                trace("delay expected", null);
                continue;
              }
              trace("delay exceeded " + uiTimeoutCount, null);

              // Take increasingly more drastic steps
              // based upon how long the delay continues

              switch (uiTimeoutCount) {
                case 0:
                  fireUITimeout(isResponsive);
                  break;
                case 1:
                  gracefulExit(isResponsive);
                  break;
                case 2:
                default:
                  forcedExit(isResponsive);
              }
              checkEventsCount = 0;
              uiTimeoutCount++;
            }
          }
        };
    monitorThread.setPriority(Thread.MIN_PRIORITY);
    monitorThread.setDaemon(true);
    monitorThread.start();
  }

  /**
   * Initialize the expected delay based upon the default expected delay.
   */
  private void initExpectedDelay() {
    var currentTime = System.currentTimeMillis();
    synchronized (lock) {
      uiBusyUntil = Math.max(uiBusyUntil, currentTime + defaultExpectedDelay);
    }
  }

  /**
   * Determine if the idle or unresponsiveness is expected
   *
   * @return <code>true</code> if expected, or <code>false</code> if the user
   * interface thread has been idle or unresponsive longer than expected
   */
  private boolean isDelayExpected() {
    var currentTime = System.currentTimeMillis();
    synchronized (lock) {
      return currentTime < uiBusyUntil;
    }
  }

  /**
   * Process condition handlers.
   *
   * @return <code>true</code> if at least one condition was handled
   */
  private boolean processConditions() {
    trace("processing conditions", null);
    var monitor = (IConditionMonitor) uiContext.getAdapter(IConditionMonitor.class);
    return monitor.process(uiContext) != IConditionMonitor.PROCESS_NONE;
  }

  /**
   * Check if events were processed during the last call to {@link #checkEventsProcessed()}.
   *
   * @return <code>true</code> if events were processed, else <code>false</code>
   */
  private boolean wereEventsProcessed() {
    synchronized (lock) {
      return uiEventProcessed;
    }
  }

  /**
   * Setup a test to see if the UI thread is still processing events. Assume that event listeners
   * have already been added to update _uiEventProcessed. Use {@link #wereEventsProcessed()} to
   * determine if events were processed, but check {@link #hasTestEnded()} first.
   */
  private void checkEventsProcessed() {
    synchronized (lock) {
      uiEventProcessed = false;
    }
    try {
      Thread.sleep(1000);
    } catch (InterruptedException e) {
      // ignored
    }
  }

  /**
   * Called by subclasses to indicate that events were processed and to adjust the expected busy
   * time.
   */
  protected void markEventProcessed() {
    var currentTime = System.currentTimeMillis();
    synchronized (lock) {
      uiEventProcessed = true;
      uiBusyUntil = Math.max(uiBusyUntil, currentTime + defaultExpectedDelay);
    }
  }

  /**
   * Called by subclasses to indicate that the UI thread was responsive for the current period of
   * time.
   */
  protected void markUIThreadResponsive() {
    synchronized (lock) {
      uiThreadResponsive = true;
    }
  }

  /**
   * Add event listeners to monitor events being processed by the UI.
   */
  protected abstract void addEventListeners();

  /**
   * Remove the event listeners added to monitor events being processed by the UI.
   */
  protected abstract void removeEventListeners();

  /**
   * Wait for up to one second to determine if the user interface thread is responsive and
   * processing new events.
   *
   * @return <code>true</code> if the user interface thread is responsive, or
   * <code>false</code> if it has not processed any new events within the last
   * one second
   */
  protected abstract boolean isUIThreadResponsive();

  /**
   * Determine if the test has ended.
   *
   * @return <code>true</code> if test has ended, else <code>false</code>
   */
  protected abstract boolean hasTestEnded();

  /**
   * FOR TESTING PURPOSES ONLY! Enable or diable console level tracing for testing.
   */
  public static void setConsoleTracing(boolean enabled) {
    if (enabled) {
      traceMode = TRACE_CONSOLE;
    } else {
      traceMode = TRACE_UNINITIALIZED;
    }
  }

  /**
   * Tracing support
   *
   * @param message the trace message
   * @param value   additional trace information
   */
  protected void trace(String message, long value) {
    if (traceMode == TRACE_OFF) {
      return;
    }
    trace(message, (Long) value);
  }

  /**
   * Tracing support
   *
   * @param message the trace message
   * @param value   additional trace information or <code>null</code> if none
   */
  protected void trace(String message, Object value) {
    // TODO [author=Dan] move functionality into new instance of existing Tracer class
    // in debug plugin
    if (traceMode == TRACE_OFF) {
      return;
    }
    var currentTime = System.currentTimeMillis();

    var buf = new StringBuilder(100);
    buf.append("UIThreadMonitor: ")
        .append(currentTime)
        .append(" ")
        .append(uiBusyUntil)
        .append(" ")
        .append(message);
    if (value != null) {
      buf.append(" ").append(value);
    }
    if (traceMode == TRACE_CONSOLE) {
      System.out.println(buf);
    } else {
      Logger.log(IRuntimePluginTraceOptions.UI_THREAD_MONITOR, buf.toString());
    }
  }

  /**
   * Generate a result file immediately before {@link #gracefulExit(boolean)} terminates the
   * application under test.
   *
   * @param isResponsive <code>true</code> if the UI thread is responsive to new user
   *                     input, and <code>false</code> if the user interface has not processed any
   *                     new events recently and may be hung.
   */
  protected void generateResults(boolean isResponsive) {
    var resultPathKey = "test.result.xml";
    var resultPath = System.getProperty(resultPathKey);
    if (resultPath == null) {
      var message =
          "The system property " + resultPathKey + " is undefined, so no XML result file generated";
      Logger.log(message);
      return;
    }

    PrintWriter writer;
    try {
      writer = new PrintWriter(new BufferedWriter(new FileWriter(new File(resultPath))));
    } catch (IOException e) {
      var message =
          "The system property " + resultPathKey + " is defined, but failed to open " + resultPath;
      Logger.log(message, e);
      return;
    }

    try {
      writeResults(writer, isResponsive);
    } finally {
      writer.close();
    }

    var message =
        "The system property "
            + resultPathKey
            + " is defined, and the result file generated: "
            + resultPath;
    Logger.log(message);
  }

  /**
   * Generate a result file immediately before {@link #gracefulExit(boolean)} terminates the
   * application under test.
   *
   * @param isResponsive <code>true</code> if the UI thread is responsive to new user
   *                     input, and <code>false</code> if the user interface has not processed any
   *                     new events recently and may be hung.
   */
  protected void writeResults(PrintWriter writer, boolean isResponsive) {
    var testClassnameKey = "test.classname";
    var testClassname = System.getProperty(testClassnameKey);
    if (testClassname == null) {
      testClassname = "unknown-test-class";
      var message =
          "The system property "
              + testClassnameKey
              + " is undefined, so report will show testcase classname as "
              + testClassname;
      Logger.log(message);
    }

    var errMsg = "UI thread monitor terminated application ";
    if (isResponsive) {
      errMsg += "because no UI activity";
    } else {
      errMsg += "because UI thread was unresponsive";
    }

    var errDetails = sanitize(stackTraces);

    writer.println("<?xml version=\"1.0\" encoding=\"UTF-8\" ?>");
    writer.println(
        "<testsuite errors=\"1\" failures=\"0\" name=\""
            + testClassname
            + "\" tests=\"1\" time=\"1\">");
    writer.println("  <properties>");

    for (Object o : new TreeSet<>(System.getProperties().keySet())) {
      var key = (String) o;
      var value = sanitize(System.getProperty(key));
      writer.println("    <property name=\"" + key + "\" value=\"" + value + "\"/>");
    }
    writer.println("  </properties>");
    writer.println(
        "  <testcase classname=\"" + testClassname + "\" name=\"testUnknown\" time=\"1\">");

    if (screenCapture != null) {
      writer.println(
          "    <screencapture"
              + " name=\""
              + sanitize(screenCapture.getName())
              + "\" href=\""
              + sanitize(screenCapture.getParentFile().getName())
              + "/"
              + sanitize(screenCapture.getName())
              + "\" file=\""
              + sanitize(screenCapture.getAbsolutePath())
              + "\"/>");
    }
    writer.print(
        "    <error message=\"" + errMsg + "\" type=\"" + RuntimeException.class.getName() + "\">");
    writer.print(errDetails);
    writer.println("    </error>");
    writer.println("  </testcase>");
    writer.println("  <system-out><![CDATA[]]></system-out>");
    writer.println("  <system-err><![CDATA[]]></system-err>");
    writer.println("</testsuite>");
  }

  /**
   * Convert raw strings into strings safe for inclusion in an XML file by replacing specific
   * characters invalid in an XML file with their expanded counterparts (e.g. replace " with
   * &quot;).
   *
   * @param value the original value (not null)
   * @return the sanitized string (not null)
   */
  protected String sanitize(String value) {
    var result = replaceAll(value, "\"", "&quot;");
    result = replaceAll(result, "<", "&lt;");
    return result;
  }

  /**
   * Replace every occurance within the given string of a substring that matches the given pattern
   * with the given replacement string. The pattern cannot contain any wildcards.
   *
   * @param string      the string in which replacements are made
   * @param pattern     the pattern used to find the substrings to be replaced
   * @param replacement the string used to replace matching substrings
   */
  protected static String replaceAll(String string, String pattern, String replacement) {
    var stringLength = string.length();
    var patternLength = pattern.length();
    if (stringLength == 0 || patternLength == 0) {
      return string;
    }

    var builder = new StringBuilder();

    var index = 0;
    while (index < stringLength) {
      if (string.startsWith(pattern, index)) {
        builder.append(replacement);
        index += patternLength;
      } else {
        builder.append(string.charAt(index));
        index++;
      }
    }
    return builder.toString();
  }
}
