<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>io.github.r4fterman</groupId>
        <artifactId>com.windowtester</artifactId>
        <version>5.14.1-SNAPSHOT</version>
    </parent>

    <artifactId>com.windowtester.junit5</artifactId>
    <name>Windowtester JUnit5</name>
    <description>Library provides extension for JUnit5. It is mandatory when running Windowtester on
        JUnit5.
    </description>

    <dependencies>
        <dependency>
            <groupId>io.github.r4fterman</groupId>
            <artifactId>com.windowtester.swing.runtime</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-api</artifactId>
        </dependency>
    </dependencies>

</project>